# Generated by Django 6.0 on 2026-01-14 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('escrow_created', 'Escrow Created'), ('escrow_funded', 'Escrow Funded'), ('escrow_cancelled', 'Escrow Cancelled'), ('milestone_submitted', 'Milestone Submitted'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('milestone_released', 'Funds Released'), ('dispute_raised', 'Dispute Raised'), ('dispute_response', 'Dispute Response'), ('dispute_resolved', 'Dispute Resolved'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('reminder', 'Reminder'), ('security_alert', 'Security Alert')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body_html', models.TextField()),
                ('email_body_text', models.TextField()),
                ('sms_body', models.CharField(max_length=160)),
                ('push_title', models.CharField(max_length=100)),
                ('push_body', models.CharField(max_length=255)),
                ('in_app_title', models.CharField(max_length=255)),
                ('in_app_body', models.TextField()),
                ('available_variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('type_preferences', models.JSONField(default=dict)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('email_digest', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('escrow_created', 'Escrow Created'), ('escrow_funded', 'Escrow Funded'), ('escrow_cancelled', 'Escrow Cancelled'), ('milestone_submitted', 'Milestone Submitted'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('milestone_released', 'Funds Released'), ('dispute_raised', 'Dispute Raised'), ('dispute_response', 'Dispute Response'), ('dispute_resolved', 'Dispute Resolved'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payout_initiated', 'Payout Initiated'), ('payout_completed', 'Payout Completed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('reminder', 'Reminder'), ('security_alert', 'Security Alert')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('channels', models.JSONField(default=list)),
                ('delivery_status', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_6b5847_idx'), models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__519f8a_idx')],
            },
        ),
    ]
