# Generated by Django 6.0 on 2026-01-14 11:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Standard, Professional, Enterprise', max_length=50, unique=True)),
                ('escrow_fee_percent', models.DecimalField(decimal_places=2, help_text='Transaction fee percentage (e.g. 1.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sla_hours', models.PositiveIntegerField(help_text='Time in hours before a dispute escalates or auto-resolves.')),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_dedicated_support', models.BooleanField(default=False)),
                ('has_white_labeling', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['escrow_fee_percent'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('custom_sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('branding_config', models.JSONField(blank=True, default=dict, help_text='Custom logos, colors, domain settings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_overrides',
            },
        ),
    ]
