# Generated by Django 6.0 on 2026-01-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseoverride',
            name='branding_config',
        ),
        migrations.AddField(
            model_name='enterpriseoverride',
            name='dedicated_support',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterpriseoverride',
            name='white_label_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom logos, colors, domain settings (replaces branding_config).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_transaction_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed transaction amount.', max_digits=15, null=True),
        ),
    ]
