# Generated by Django 6.0 on 2026-01-13 10:39

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruling', models.CharField(choices=[('favor_buyer', 'Favor Buyer (Full Refund)'), ('favor_seller', 'Favor Seller (Full Release)'), ('split', 'Split Decision'), ('partial_refund', 'Partial Refund'), ('mutual_cancellation', 'Mutual Cancellation')], max_length=30)),
                ('reasoning', models.TextField()),
                ('buyer_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('seller_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('arbitration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('fee_paid_by', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('split', 'Split'), ('platform', 'Platform')], default='split', max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('can_appeal', models.BooleanField(default=True)),
                ('appeal_deadline', models.DateTimeField(blank=True, null=True)),
                ('supporting_documents', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arbitration_decisions',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('not_as_described', 'Item Not As Described'), ('not_received', 'Item Not Received'), ('quality_issue', 'Quality Issue'), ('incomplete_work', 'Incomplete Work'), ('late_delivery', 'Late Delivery'), ('fraud', 'Suspected Fraud'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('awaiting_evidence', 'Awaiting Evidence'), ('arbitration', 'In Arbitration'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField()),
                ('resolution_deadline', models.DateTimeField()),
                ('escalation_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('accepts_claim', models.BooleanField(null=True)),
                ('counter_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispute_responses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispute_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(max_length=50)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('text_content', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'db_table': 'evidence',
                'ordering': ['created_at'],
            },
        ),
    ]
