# Generated by Django 6.0 on 2026-01-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationdecision',
            name='arbitrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arbitration_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='assigned_arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitrated_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='escrow.escrowaccount'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbitrationdecision',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeresponse',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputetimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputetimeline',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['escrow', 'status'], name='disputes_escrow__e5fd14_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_arbitrator', 'status'], name='disputes_assigne_14b723_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'resolution_deadline'], name='disputes_status_898f08_idx'),
        ),
    ]
