# Generated by Django 6.0 on 2026-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='evidence_folder_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Standard=0, Pro=10, Enterprise=100'),
        ),
    ]
