# Generated by Django 6.0 on 2026-01-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The pricing/feature plan assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='plans.plan'),
        ),
    ]
