# Generated by Django 6.0 on 2026-01-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_escrowaccount_auto_release_at_and_more'),
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for Credit, Negative for Debit', max_digits=15)),
                ('entry_type', models.CharField(choices=[('funding', 'Funding'), ('payout', 'Payout'), ('fee_collection', 'Fee Collection'), ('refund', 'Refund')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='escrow.escrowaccount')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['escrow', 'entry_type'], name='ledger_entr_escrow__11416b_idx'), models.Index(fields=['account', 'created_at'], name='ledger_entr_account_14b5c0_idx')],
            },
        ),
    ]
