# Generated by Django 6.0 on 2026-01-13 10:39

import apps.escrow.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, default=apps.escrow.models.generate_reference_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('in_verification', 'In Verification'), ('milestone_pending', 'Milestone Pending'), ('partially_released', 'Partially Released'), ('fully_released', 'Fully Released'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='created', max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('created', 'Created'), ('funded', 'Funded'), ('in_verification', 'In Verification'), ('milestone_pending', 'Milestone Pending'), ('partially_released', 'Partially Released'), ('fully_released', 'Fully Released'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], max_length=30, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('escrow_type', models.CharField(choices=[('freelance', 'Freelance Contract'), ('ecommerce', 'E-Commerce'), ('real_estate', 'Real Estate'), ('vehicle', 'Vehicle Transaction'), ('digital_service', 'Digital Service'), ('general', 'General Transaction')], default='general', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand')], default='USD', max_length=3)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('terms', models.JSONField(default=dict)),
                ('inspection_period_days', models.PositiveIntegerField(default=3)),
                ('auto_release_days', models.PositiveIntegerField(default=14)),
                ('conditions', models.JSONField(default=dict)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escrow_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_contract', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escrow_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escrow_invitations',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released')], default='pending', max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deliverables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
