# Generated by Django 6.0 on 2026-01-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrows_as_arbitrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowdocument',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='escrow.escrowaccount'),
        ),
        migrations.AddField(
            model_name='escrowdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowinvitation',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='escrow.escrowaccount'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='escrow.escrowaccount'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['reference_code'], name='escrow_acco_referen_98b0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['buyer', 'status'], name='escrow_acco_buyer_i_fa6e08_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['seller', 'status'], name='escrow_acco_seller__f7c3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['status', 'expires_at'], name='escrow_acco_status_12be79_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['status', 'created_at'], name='escrow_acco_status_a91c41_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['escrow', 'status'], name='milestones_escrow__3ea23a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['escrow', 'order'], name='milestones_escrow__db89f1_idx'),
        ),
    ]
