# Generated by Django 6.0 on 2026-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, help_text='When funds unlock automatically.', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='fee_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual fee amount calculated at creation.', max_digits=15, null=True),
        ),
    ]
