# Generated by Django 6.0 on 2026-01-13 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('fund', 'Fund'), ('release', 'Release'), ('refund', 'Refund'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected')], db_index=True, max_length=50)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('previous_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('data', models.JSONField()),
                ('summary', models.JSONField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('stack_trace', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'system_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
