# Generated by Django 6.0 on 2026-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('fund', 'Fund'), ('release', 'Release'), ('refund', 'Refund'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('STATUS_CHANGE', 'Status Change'), ('FUNDS_RELEASE', 'Funds Release')], db_index=True, max_length=50),
        ),
    ]
